export const locales = ["en", "nl"] as const;
export type Locale = (typeof locales)[number];

export function isLocale(value: string): value is Locale { return locales.includes(value as Locale); }

export const copy = {
  en: {
    navigation: { directory: "Directory", contribute: "Contribute", addListing: "Add a listing" }, footer: "A shared record of Dutch beer, built with care.",
    home: { eyebrow: "An independent, community project", title: "Every Dutch beer", titleEmphasis: "has a story.", intro: "Dutch.beer is building a shared, source-aware map of the breweries and beers that make the Netherlands worth exploring.", explore: "Explore the directory", add: "Add what you know", note: "The directory is just getting started. Help make it trustworthy.", recordEyebrow: "A better beer record", recordTitle: "Made for curious drinkers. Useful to everyone.", recordCopy: "Finding Dutch beer should not depend on stale listings or closed platforms. We’re creating a durable public record—with room for local knowledge and direct brewery input.", principles: [["Open by default", "Profiles, sources, and edits are made for the community—not locked away."], ["Traceable facts", "Every important detail can carry a source, date, and a clear confidence signal."], ["Built together", "Enthusiasts and breweries can improve the record, one useful correction at a time."]], bannerEyebrow: "Start the record", bannerTitle: "Know a brewery?", bannerTitleSecond: "Put it on the map." },
    directory: { breweries: { title: "The brewery directory", description: "A growing, community-maintained record of independent Dutch breweries.", empty: "The first breweries are waiting.", action: "Contribute a brewery" }, beers: { title: "The beer directory", description: "A place for every Dutch beer—documented with care and source-aware details.", empty: "The first beers are waiting.", action: "Contribute a beer" }, emptyCopy: "We don’t seed this project with unverified information. Be part of the first trusted entries instead." },
    contribute: { eyebrow: "Contribute", title: "Make the record", emphasis: "more useful.", lead: "Have a source or a correction? Start here. Contributions will be reviewable, attributed where appropriate, and connected to the evidence behind them.", options: [["Add a brewery", "Help establish a new brewery profile with its official website and location.", "Send a brewery tip"], ["Add a beer", "Document a beer and its source so other people can build on it.", "Send a beer tip"], ["Correct a detail", "Spot something inaccurate later? Corrections are an essential contribution.", "Share a correction"]], trustTitle: "How we handle trust", trustCopy: "New submissions are recorded with their source and reviewed before publication. Official brewery-domain contributors can later claim and maintain their profiles." },
  },
  nl: {
    navigation: { directory: "Gids", contribute: "Bijdragen", addListing: "Vermelding toevoegen" }, footer: "Een gedeeld overzicht van Nederlands bier, met zorg gemaakt.",
    home: { eyebrow: "Een onafhankelijk gemeenschapsproject", title: "Elk Nederlands bier", titleEmphasis: "heeft een verhaal.", intro: "Dutch.beer bouwt aan een gedeelde kaart met bronnen van de brouwerijen en bieren die Nederland zo bijzonder maken.", explore: "Bekijk de gids", add: "Deel wat je weet", note: "De gids staat nog aan het begin. Help mee om hem betrouwbaar te maken.", recordEyebrow: "Een beter bieroverzicht", recordTitle: "Voor nieuwsgierige drinkers. Nuttig voor iedereen.", recordCopy: "Nederlands bier vinden zou niet moeten afhangen van verouderde lijsten of gesloten platforms. We maken een duurzaam openbaar overzicht, met ruimte voor lokale kennis en input van brouwerijen.", principles: [["Open als uitgangspunt", "Profielen, bronnen en aanpassingen zijn voor de gemeenschap gemaakt—niet achter gesloten deuren."], ["Herleidbare feiten", "Elk belangrijk detail kan een bron, datum en duidelijk betrouwbaarheidssignaal krijgen."], ["Samen gebouwd", "Liefhebbers en brouwerijen kunnen het overzicht verbeteren, met één nuttige correctie tegelijk."]], bannerEyebrow: "Begin het overzicht", bannerTitle: "Ken je een brouwerij?", bannerTitleSecond: "Zet haar op de kaart." },
    directory: { breweries: { title: "De brouwerijgids", description: "Een groeiend, door de gemeenschap onderhouden overzicht van onafhankelijke Nederlandse brouwerijen.", empty: "De eerste brouwerijen wachten nog.", action: "Draag een brouwerij bij" }, beers: { title: "De biergids", description: "Een plek voor elk Nederlands bier—zorgvuldig vastgelegd met duidelijke bronnen.", empty: "De eerste bieren wachten nog.", action: "Draag een bier bij" }, emptyCopy: "We vullen dit project niet met ongecontroleerde informatie. Help mee met de eerste betrouwbare vermeldingen." },
    contribute: { eyebrow: "Bijdragen", title: "Maak het overzicht", emphasis: "nog nuttiger.", lead: "Heb je een bron of correctie? Begin hier. Bijdragen kunnen worden beoordeeld, waar passend toegeschreven en gekoppeld aan het bewijs erachter.", options: [["Voeg een brouwerij toe", "Help een nieuw brouwerijprofiel opzetten met de officiële website en locatie.", "Stuur een brouwerijtip"], ["Voeg een bier toe", "Leg een bier en zijn bron vast, zodat anderen erop kunnen voortbouwen.", "Stuur een biertip"], ["Corrigeer een detail", "Zie je later iets dat niet klopt? Correcties zijn een essentiële bijdrage.", "Deel een correctie"]], trustTitle: "Zo behandelen we vertrouwen", trustCopy: "Nieuwe inzendingen worden met hun bron vastgelegd en vóór publicatie beoordeeld. Bijdragers met een officieel brouwerijdomein kunnen later hun profiel claimen en bijhouden." },
  },
} as const;
